apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: geoint
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "geoint-app"
        metrics_path: /metrics
        static_configs:
          - targets: ["geoint-app.geoint.svc.cluster.local:80"]
