apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: geoint
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: geointuser
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  APP_HOST: "0.0.0.0"
  APP_PORT: "5000"

