apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoint-ingress
  namespace: geoint
spec:
  rules:
    - host: geoint.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geoint-app
                port:
                  number: 80
